# Generated by Django 5.0.3 on 2024-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlwebsite', '0003_candidate_election_result_vote_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
